-- ============================================================
-- Blogdetareas · Blog UNSM FISI
-- CÓMO USAR: abre tu proyecto en https://supabase.com/dashboard
--   → SQL Editor → New query → pega TODO este script → Run
--   (una sola vez, toma menos de un minuto)
-- ============================================================

-- ------------------------------------------------------------
-- 1) Perfiles de usuario
-- ------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text not null default '',
  role text not null default 'student' check (role in ('student', 'admin')),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

-- El PRIMER usuario que se registre en el blog será el administrador.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  n_admin int;
begin
  select count(*) into n_admin from public.profiles where role = 'admin';
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)),
    case when n_admin = 0 then 'admin' else 'student' end
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Función: ¿el usuario actual es administrador?
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

grant execute on function public.is_admin() to anon, authenticated;
grant select on public.profiles to anon, authenticated;

-- ------------------------------------------------------------
-- 2) Trabajos (un trabajo por cada Unidad + Semana)
-- ------------------------------------------------------------
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  unit smallint not null check (unit between 1 and 3),
  week smallint not null check (week between 1 and 14),
  title text not null,
  description text not null default '',
  content text not null default '',
  file_url text,
  file_path text,
  file_name text,
  author_id uuid references public.profiles (id) on delete set null,
  author_name text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (unit, week)
);

alter table public.posts enable row level security;

-- ------------------------------------------------------------
-- 3) Comentarios
-- ------------------------------------------------------------
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  content text not null check (char_length(content) between 1 and 1000),
  created_at timestamptz not null default now()
);

alter table public.comments enable row level security;

-- ------------------------------------------------------------
-- 4) Políticas de seguridad (RLS)
-- ------------------------------------------------------------
-- Lectura pública de trabajos
create policy "posts_lectura_publica" on public.posts
  for select to anon, authenticated using (true);

-- Solo administradores escriben / editan / borran trabajos
create policy "posts_insercion_admin" on public.posts
  for insert to authenticated with check (public.is_admin());

create policy "posts_edicion_admin" on public.posts
  for update to authenticated using (public.is_admin());

create policy "posts_borrado_admin" on public.posts
  for delete to authenticated using (public.is_admin());

-- Lectura pública de comentarios
create policy "comments_lectura_publica" on public.comments
  for select to anon, authenticated using (true);

-- Cualquier usuario con sesión puede comentar
create policy "comments_insercion_autenticado" on public.comments
  for insert to authenticated with check (auth.uid() = user_id);

-- Cada usuario borra solo sus propios comentarios
create policy "comments_borrado_autor" on public.comments
  for delete to authenticated using (auth.uid() = user_id);

-- ------------------------------------------------------------
-- 5) Permisos para el Data API (PostgREST)
-- ------------------------------------------------------------
grant select on public.posts to anon, authenticated;
grant insert, update, delete on public.posts to authenticated;

grant select on public.comments to anon, authenticated;
grant insert, update, delete on public.comments to authenticated;

-- ------------------------------------------------------------
-- 6) Almacenamiento: bucket "trabajos"
-- ------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('trabajos', 'trabajos', true)
on conflict (id) do nothing;

-- Descarga pública de los archivos
drop policy if exists "trabajos_lectura_publica" on storage.objects;
create policy "trabajos_lectura_publica" on storage.objects
  for select using (bucket_id = 'trabajos');

-- Solo administradores suben / editan / borran archivos
drop policy if exists "trabajos_escritura_admin" on storage.objects;
create policy "trabajos_escritura_admin" on storage.objects
  for insert with check (bucket_id = 'trabajos' and public.is_admin());

drop policy if exists "trabajos_edicion_admin" on storage.objects;
create policy "trabajos_edicion_admin" on storage.objects
  for update using (bucket_id = 'trabajos' and public.is_admin());

drop policy if exists "trabajos_borrado_admin" on storage.objects;
create policy "trabajos_borrado_admin" on storage.objects
  for delete using (bucket_id = 'trabajos' and public.is_admin());

-- ------------------------------------------------------------
-- 7) Corrección de la secuencia de identidad (aplica siempre)
-- ------------------------------------------------------------
select setval(
  pg_get_serial_sequence('public.posts', 'id'),
  coalesce((select max(id) from public.posts), 0) + 1,
  false
);

select setval(
  pg_get_serial_sequence('public.comments', 'id'),
  coalesce((select max(id) from public.comments), 0) + 1,
  false
);

-- Fin del script. Si no hay errores en verde, ¡listo!